In [4]:
import numpy as np

Task 1

In [5]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 2

In [6]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 3

In [7]:
print(b[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 4

In [8]:
a = np.arange(9).reshape((3,3))
print (a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 5

In [9]:
a = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(a))

(array([0, 1, 4]),)


Task 6

In [10]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 7 

In [11]:
a = np.random.rand(9).reshape((3,3))
print(a)
print(f"max value is: {np.max(a)}")
print(f"min value is: {np.min(a)}")

[[0.90745368 0.43176749 0.43012429]
 [0.9129177  0.93912199 0.81761299]
 [0.67295874 0.83898269 0.38827147]]
max value is: 0.9391219876785929
min value is: 0.3882714670804922


Task 8

In [12]:
a = np.random.rand(5,5)
print(a)

[[0.2332169  0.86658109 0.24323275 0.82729981 0.96781206]
 [0.93447975 0.85395309 0.49098565 0.17709493 0.72375143]
 [0.9292055  0.02930908 0.58237878 0.54385894 0.2767172 ]
 [0.19301268 0.84843624 0.34472385 0.3360327  0.34553915]
 [0.11606549 0.08952185 0.44018659 0.82916015 0.31166344]]


Task 9

In [13]:
array = np.array([1, 3, 5, 11, 15, 20, 25])
target = 14
index_closest = np.abs(array - target).argmin()

print(array[index_closest])

15


Task 10

In [14]:
array = np.array([[5, 9, 3], [10, 2, 15], [6, 7, 8]])

index_max = array.argmax()
row, col = np.unravel_index(index_max, array.shape)

array[row][col] = 0

print(array)



[[ 5  9  3]
 [10  2  0]
 [ 6  7  8]]


Task 11

In [21]:
array = np.array([2, 3, 2, 5, 8, 3, 3, 7, 2, 3, 5, 5, 5, 5])

num, counts = np.unique(array, return_counts=True)
MostCommon = num[counts.argmax()]

print(f"most common value is: {MostCommon}")


most common value is: 5


Task 12

In [24]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrayT = np.transpose(array)
print (array @ arrayT)

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


Task 13

In [17]:
matrix = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print (np.linalg.det(matrix))


-306.0


Task 14

In [18]:
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det = np.linalg.det(matrix)

if det != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print(f"inverse is: {inverse_matrix}")
else:
    print("inverse does not exist, matrix is singular")


inverse is: [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
